name: st127262-car-price-app

services:
  web-st127262:
    image: lucjawojtowicz/car-price-app:latest
    container_name: st127262-web
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.web-st127262.rule=Host(`web-st127262.ml.brain.cs.ait.ac.th`)"
      - "traefik.http.routers.web-st127262.entrypoints=websecure"
      - "traefik.http.routers.web-st127262.tls=true"
      - "traefik.http.routers.web-st127262.tls.certresolver=letsencrypt"
      - "traefik.http.services.web-st127262.loadbalancer.server.port=8000"
    networks:
      - default
      - web

networks:
  default:
  web:
    external: true